version: '3.8'

services:
  satis:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: satis-image:latest
    container_name: satis-server
    ports:
      - "8080:80"
    restart: unless-stopped
