version: '3.8'

networks:
    nw-vault-composer:
        driver: bridge
        name: nw-vault-composer 
services:
  satis:
    build:
      context: .
      dockerfile: Dockerfile
    image: satis-image:latest
    container_name: satis-server
    ports:
      - "10310:80"
    restart: unless-stopped
    networks:
      - nw-vault-composer
