name: Build and Deploy Satis

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build imagem do Satis
        run: |
            docker compose build
    
      - name: Create container e geração do Satis
        run: |
          docker create --name satis-server satis-image
          mkdir -p public
          docker cp satis-server:/satis/public/. ./public

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          
      - name: Limpar container e imagem do Satis
        run: |
          docker rm -f satis-server || true
          docker rmi -f satis-image || true
