name: Build and Deploy Satis

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build imagem do Satis
        run: |
            docker compose build
    
      - name: Build da imagem e geração do Satis
        run: |
          docker create --name satis-server satis-image
          mkdir -p public
          docker cp satis-server:/satis/public/. ./public
          docker rm satis-server
          docker rmi satis-image

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
