# .github/workflows/deploy.yml
name: Deploy Satis

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Satis in Docker
        run: |
          mkdir public dist
          docker run --rm \
            -v ${{ github.workspace }}/satis.json:/satis.json \
            -v ${{ github.workspace }}/packages:/packages \
            -v ${{ github.workspace }}/public:/public \
            -v ${{ github.workspace }}/dist:/dist \
            composer/satis build /satis.json /public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
